# This is a basic workflow to help you get started with Actions

name: Publish to Packages

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ModuleTools module form PSGallery
        run: |
          Install-PSResource -Repository PSGallery -Name ModuleTools -TrustRepository

      - name: Build Module
        run: Invoke-MTBuild -Verbose

      - name: Run Pester Tests
        run: Invoke-MTTest

      - name: List files
        run: Get-ChildItem ./dist -Recurse

      - name: Publish Package to Github
        run: |
          Publish-PSResource -Path ./dist/ModuleTools -Repository PSGallery -ApiKey $Env:ApiKey
        env:
          ApiKey: ${{ secrets.PSGALLERY_API }}